backend:
    name: github
    repo: tlorent/gatsby-fitness-site

media_folder: static/images
locale: 'nl'

collections:
    - name: content
      label: Content
      files:
          - label: 'Header Section'
            name: 'header'
            file: 'content/header.md'
            fields:
                - { name: title, label: title, widget: string, required: true }
                - {
                      name: subtitle,
                      label: subtitle,
                      widget: string,
                      required: true,
                  }
                - { name: tagline, label: tagline, widget: string }
          - label: 'About Section'
            name: 'about'
            file: 'content/about.md'
            fields:
                - { name: title, label: title, widget: string, required: true }
                - { name: quote, label: quote, widget: string, required: true }
                - {
                      name: about text paragraph one,
                      label: about text paragraph one,
                      widget: text,
                      required: true,
                  }
                - {
                      name: about text paragraph two,
                      label: about text paragraph two,
                      widget: text,
                  }
                - {
                      name: about text paragraph three,
                      label: about text paragraph three,
                      widget: text,
                  }
