backend:
    name: github
    repo: tlorent/gatsby-fitness-site

media_folder: static/images
public_folder: /images

publish_mode: editorial_workflow
locale: 'nl'
editor:
    preview: false

collections:
    - name: blog
      label: Blog
      folder: 'content/blog'
      create: true
      slug: "{{title}}"
      preview_path: "blog/{{slug}}"
      fields:
        - { label: Title, name: title, widget: string }
        - { label: Date, name: date, widget: date, required: true }
        - { label: Category, name: category, widget: select, options: ["Fitness", "Diet", "Motivation"], required: true }
        - { label: Author, name: author, widget: select, options: ["Ben Dobson", "Jane Dobson"], required: true }
        - label: "Author Image"
          name: "author-image"
          widget: "select"
          required: true
          options:
          - { label: "Ben Dobson", value: "https://res.cloudinary.com/ded0rxgui/image/upload/c_thumb,w_200,g_face/v1605604833/free-to-use-sounds-ObbDrFOudbY-unsplash_gzg4yw.jpg" }
          - { label: "Jane Dobson", value: "https://res.cloudinary.com/ded0rxgui/image/upload/c_thumb,w_200,g_face/v1605604834/shin-enn-yapp-87iEXHGIDnU-unsplash_nyhjcc.jpg" }
        - { label: Text, name: text, widget: text }
    - name: content
      label: Content
      preview_path: "/"
      view_filters:
          - label: 'Content uit 2020'
            field: date
            pattern: '2020'
      files:
          - label: 'Header Section'
            name: 'header'
            file: 'content/header.md'
            fields:
                - { name: title, label: title, widget: string, required: true }
                - { name: headerImage, label: header image, widget: image, required: true }
                - {
                      name: subtitle,
                      label: subtitle,
                      widget: string,
                      required: true,
                  }
                - { name: tagline, label: tagline, widget: string }
          - label: 'About Section'
            name: 'about'
            file: 'content/about.md'
            fields:
                - { name: title, label: title, widget: string, required: true }
                - { name: quote, label: quote, widget: string, required: true }
                - {
                      name: body,
                      label: about text,
                      widget: markdown,
                      required: true,
                  }
          - label: 'Trainings Section'
            name: 'training'
            file: 'content/training.md'
            fields:
                - {
                      name: titleIndividual,
                      label: title individual,
                      widget: string,
                      required: true,
                  }
                - {
                      name: individualExplanation,
                      label: individual explanation,
                      widget: string,
                      required: true,
                  }
                - {
                      name: individualImage,
                      label: individual image,
                      widget: image,
                      required: true,
                  }
                - {
                      name: individualBenefits,
                      label: individual benefits,
                      widget: list,
                      max: 3,
                      min: 1,
                      field: { label: benefit, name: benefit, widget: string },
                      required: true,
                  }
                - {
                      name: titleGroup,
                      label: title group,
                      widget: string,
                      required: true,
                  }
                - {
                      name: groupExplanation,
                      label: group explanation,
                      widget: string,
                      required: true,
                  }
                - {
                      name: groupImage,
                      label: group image,
                      widget: image,
                      required: true,
                  }
                - {
                      name: groupBenefits,
                      label: group benefits,
                      widget: list,
                      max: 3,
                      min: 1,
                      field: { label: benefit, name: benefit, widget: string },
                      required: true,
                  }
          - label: "Schedule Section"
            name: "schedule"
            file: "content/schedule.md"
            fields:
                - label: Days
                  name: days
                  widget: list
                  fields:
                    - { label: day, name: day, widget: string }
                    - label: classes
                      name: classes
                      widget: list
                      fields:
                        - { label: start, name: startTime, widget: datetime, required: true }
                        - { label: end, name: endTime, widget: datetime, required: true }
                        - { label: title, name: classTitle, widget: string, required: true }
                        - { label: location, name: location, widget: string, required: true }
          - label: "Recommendations Section"
            name: "recommendations"
            file: "content/recommendations.md"
            fields:
                - label: Recommendations
                  name: recommendations
                  widget: list
                  max: 3
                  fields:
                    - { label: quote, name: quote, widget: string, required: true }
                    - { label: clientName, name: clientName, widget: string, required: true }
                    - { label: clientYearsActive, name: clientYearsActive, widget: number, required: true }
                    - { label: clientImage, name: clientImage, widget: image, required: true }
          - label: "FAQ Section"
            name: "faq"
            file: "content/faq.md"
            fields:
                - label: FAQ
                  name: faq
                  widget: list
                  min: 1
                  max: 3
                  fields:
                    - { label: question, name: question, widget: string, required: true }
                    - { label: answer, name: answer, widget: text, required: true }
